### ISSUE TITLE
Wrong text in UI

### ISSUE THREAD

**Issue by astro-ray** [opensourcecheemsburgers/ubiquity#1]
First of all, great project. Looks beautiful, love to use it as my Markdown editor soon if it is developed more.

When testing on linux found this bug in the UI

![image](https://github.com/opensourcecheemsburgers/ubiquity/assets/69363775/c8b5cac8-7718-4bba-9ef1-c91f9d2f9f90)

**Comment by opensourcecheemsburgers** [comment]
Thanks for the heads up :) 

Currently working on some custom error toasts so I'll bundle the fix for this in with the `v0.4.0` release.

**Comment by opensourcecheemsburgers** [comment]
Fixed in the recent `v0.4.0` release, thanks :)
